name: Build & Test Bot Noti Commit

on:
  push:
    branches: [main]
    paths:
      - '**'
      - '.github/workflows/deploy_render.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
